version: '3.3'

services:
  backend:
    container_name: backend
    restart: always
    env_file: "./backend/.env"
    build: backend
    ports:
      - '3001:3001'
    links:
      - mongo
    environment:
      - PORT=3001
      - DATABASE_URL=mongodb://mongo:27017/backend

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'

  frontend:
    container_name: frontend
    restart: always
    build: frontend
    ports:
      - '3000:3000'
    environment:
      - API_HOST=backend
      - API_PORT=3001
    links:
      - backend




